export {default as Home} from './Home/Home'
export {default as Screen1} from './Screen1/Screen1'
export {default as Screen2} from './Screen2/Screen2'
export {default as Screen3} from './Screen3/Screen3'
export {default as Screen4} from './Screen4/Screen4'
export {default as Screen5} from './Screen5/Screen5'
export {default as Screen6} from './Screen6/Screen6'